import:
  fromLocal:
    enabled: true
    files:
      - ["./node_modules/sense-extension-utils/dist/general-utils.js", "./.tmp/lib/external/sense-extension-utils"]
      - ["./node_modules/sense-extension-utils/dist/pp-helper.js", "./.tmp/lib/external/sense-extension-utils"]
      - ["./node_modules/font-awesome/css/font-awesome.css", "./.tmp/lib/external/font-awesome/css"]
      - ["./node_modules/font-awesome/fonts/FontAwesome.otf", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.eot", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.svg", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.ttf", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.woff", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.woff2", "./.tmp/lib/external/font-awesome/fonts"]




      - ["./node_modules/lodash/lodash.min.js", "./.tmp/lib/external/lodash"]
wbfolder:
  enabled: false
htmlmin:
  collapseWhitespace: true
  preserveLineBreaks: false
  removeComments: true
  collapseInlineTagWhitespace: true
localExtensionDir: ""
deployment:
  toLocal:
    enabled: false
watch:
  - "./src/**/*.*"
  - "./node_modules/sense-extension-utils/dist/**/*.*"

