taskChains:
  build:
    - "shell"
    - "clean:tmp"
    - "copy:toTmp"
    - "import:fromLocal"
    - "less:reduce"
    - "replace:tmp"
    - "wbfolder:tmp"
    - "clean:tmpIllegal"
    - "jsonlint:tmp"
    - "htmlmin:tmp"
    - "cleanCss:tmp"
    - "clean:buildDev"
    - "header-js:tmp"
    - "copy:tmpToDev"
    - "zip:dev"
    - "clean:localExtensionDir"
    - "deploy:toLocal"
    - "deploy:toSsh"
    - "deploy:viaShell"
    - "clean:tmp"
    - "import:fromSsh"
  release:
    - "shell"
    - "clean:tmp"
    - "copy:toTmp"
    - "import:fromLocal"
    - "less:reduce"
    - "replace:tmp"
    # - "wbfolder:tmp" ==> doesn"t make sense since the uglified files cannot really be edited in Dev-Hub
    - "uglify:tmp"
    - "clean:tmpIllegal"
    - "jsonlint:tmp"
    - "htmlmin:tmp"
    - "minify:json:tmp"
    - "cleanCss:tmp"
    - "header-js:tmp"
    - "clean:buildRelease"
    - "copy:tmpToRelease"
    - "zip:release"
    - "zip:latest"
    - "clean:localExtensionDir"
    - "deploy:toLocal"
    - "deploy:toSsh"
    - "deploy:viaShell"
    - "clean:tmp"
import:
  fromLocal:
    enabled: true
    files:
      - ["./node_modules/font-awesome/css/font-awesome.css", "./.tmp/lib/external/font-awesome/css"]
      - ["./node_modules/font-awesome/fonts/FontAwesome.otf", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.eot", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.svg", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.ttf", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.woff", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/font-awesome/fonts/fontawesome-webfont.woff2", "./.tmp/lib/external/font-awesome/fonts"]
      - ["./node_modules/lodash/lodash.min.js", "./.tmp/lib/external/lodash"]
wbfolder:
  enabled: false
htmlmin:
  collapseWhitespace: true
  preserveLineBreaks: false
  removeComments: true
  collapseInlineTagWhitespace: true
localExtensionDir: ""
deployment:
  toLocal:
    enabled: false
watch:
  - "./src/**/*.*"

