import:
  fromLocal:
    enabled: true
    files:
      - ["./node_modules/sense-extension-utils/dist/general-utils.js", "./.tmp/lib/external/sense-extension-utils"]
      - ["./node_modules/sense-extension-utils/dist/pp-helper.js", "./.tmp/lib/external/sense-extension-utils"]
wbfolder:
  enabled: false
htmlmin:
  collapseWhitespace: true
  preserveLineBreaks: false
  removeComments: true
  collapseInlineTagWhitespace: true
localExtensionDir: ""
deployment:
  toLocal:
    enabled: false
watch:
  - "./src/**/*.*"
  - "./node_modules/sense-extension-utils/dist/**/*.*"

