version: "3.3"

volumes:
  sense-client-files:

services:

  qix:
    image: qlikcore/engine:${QIX_ENGINE_VER:-latest}
    restart: always
    container_name: qix-engine
    command: -S LockD=65522 -S DocumentDirectory=/docs -S ExtensionsDirectory=/extensions -S --WsPath /srv --MigrationPort -1  -S AcceptEULA=yes
    volumes:
      - ./example:/docs
      - sense-client-files:/srv
      - ./build/${ENV:-dev}:/extensions/sense-navigation
    ports:
      - "9076:9076"
    depends_on:
      - sense-client

  sense-client:
    image: qlik/sense-client:${SENSE_CLIENT_VER:-latest}
    container_name: sense-client
    volumes:
      - sense-client-files:/srv
    tty: true
